# -*- coding: utf-8 -*-
"""OpenAI_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTIyyJPTtoYy6_JNfBNbkYRKc6ntOAHI
"""

import os
import json
import time
import random
import hashlib
from datetime import datetime
from pathlib import Path
import numpy as np
import requests
import streamlit as st
import matplotlib.pyplot as plt

# =========================
# App Config
# =========================
st.set_page_config(page_title="玄学小助手", page_icon="🔮", layout="wide")

APP_TITLE = "🔮 玄学小助手"
DEFAULT_MODEL = "gpt-4.1-mini"
PRICE_YUAN = 4.99
CREDITS_PER_PAY = 1

CREDITS_FILE = "credits.json"
PAY_REPORTS_FILE = "pay_reports.json"
WECHAT_QR_PATH = "wechat_qr.png"  # 放在仓库根目录（和 app.py 同级）

# Tarot assets
TAROT_DIR = Path(__file__).parent / "tarot_major"   # tarot_major/ 放到 app.py 同级
TAROT_BACK = TAROT_DIR / "back.png"
TAROT_POS_LABELS = ["过去", "现在", "未来"]

# =========================
# Secrets
# =========================
OPENAI_API_KEY = st.secrets.get("OPENAI_API_KEY", os.getenv("OPENAI_API_KEY"))
ADMIN_PASSWORD = st.secrets.get("ADMIN_PASSWORD", os.getenv("ADMIN_PASSWORD"))

# =========================
# Utilities: JSON load/save
# =========================
def load_json(path: str, default):
    p = Path(path)
    if not p.exists():
        return default
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return default

def save_json(path: str, data):
    p = Path(path)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")

def now_iso():
    return datetime.now().isoformat(timespec="seconds")

# =========================
# User ID: stable & input-able
# =========================
def short_hash(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()[:8].upper()

def get_or_create_user_id() -> str:
    """
    优先级：
    1) URL ?uid=XXXX
    2) session_state 里已有
    3) 自动生成
    """
    uid = None
    try:
        qp = st.query_params
        uid = qp.get("uid", None)
        if isinstance(uid, list):
            uid = uid[0] if uid else None
    except Exception:
        try:
            qp = st.experimental_get_query_params()
            uid = qp.get("uid", [None])[0]
        except Exception:
            uid = None

    if uid:
        uid = str(uid).strip().upper()
        st.session_state["user_id"] = uid
        return uid

    if st.session_state.get("user_id"):
        return st.session_state["user_id"]

    seed = f"{time.time()}-{random.random()}"
    uid = short_hash(seed)
    st.session_state["user_id"] = uid
    return uid

def set_user_id(uid: str):
    uid = (uid or "").strip().upper()
    if not uid:
        return
    st.session_state["user_id"] = uid
    try:
        st.query_params["uid"] = uid
    except Exception:
        st.experimental_set_query_params(uid=uid)

# =========================
# Credits
# =========================
def get_credits(uid: str) -> int:
    data = load_json(CREDITS_FILE, {})
    return int(data.get(uid, 0))

def add_credits(uid: str, n: int) -> int:
    data = load_json(CREDITS_FILE, {})
    data[uid] = int(data.get(uid, 0)) + int(n)
    save_json(CREDITS_FILE, data)
    return data[uid]

def consume_one_credit(uid: str) -> bool:
    data = load_json(CREDITS_FILE, {})
    cur = int(data.get(uid, 0))
    if cur <= 0:
        return False
    data[uid] = cur - 1
    save_json(CREDITS_FILE, data)
    return True

# =========================
# Payment reports (manual confirm)
# =========================
def log_pay_intent(uid: str, amount: float, note: str):
    rec = {
        "user_id": uid,
        "amount": amount,
        "note": note,
        "status": "pending",
        "submitted_at": now_iso(),
    }
    with open(PAY_REPORTS_FILE, "a", encoding="utf-8") as f:
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")

def read_pay_reports(limit=200):
    p = Path(PAY_REPORTS_FILE)
    if not p.exists():
        return []
    lines = p.read_text(encoding="utf-8").splitlines()
    rows = []
    for line in lines[-limit:]:
        line = line.strip()
        if not line:
            continue
        try:
            rows.append(json.loads(line))
        except Exception:
            pass
    return rows

# =========================
# OpenAI call (Chat Completions)
# =========================
SYSTEM_STYLE = """你是一个温柔、共情、会安慰人的中文玄学解读师（娱乐用途）。
原则：
- 不制造恐惧，不下“绝对会发生/一定完蛋”的断言
- 用“可能/倾向/建议”表达
- 结构清晰：共情 → 解读 → 可执行建议（3条）→ 温柔收尾
- 若用户信息不足，先给出合理假设并提醒可补充信息
- 最后加免责声明：仅供娱乐与自我反思，不替代医疗/法律/投资建议
"""

def call_openai_messages(messages, model=DEFAULT_MODEL, temperature=0.8) -> str:
    if not OPENAI_API_KEY:
        return "❌ 缺少 OPENAI_API_KEY（请在 Streamlit Cloud Secrets 或本地 .streamlit/secrets.toml 设置）。"

    url = "https://api.openai.com/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {OPENAI_API_KEY}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
    }
    r = requests.post(url, headers=headers, json=payload, timeout=90)
    if r.status_code != 200:
        return f"❌ OpenAI 调用失败：HTTP {r.status_code}\n\n{r.text}"
    data = r.json()
    return data["choices"][0]["message"]["content"]

def build_messages(kind: str, payload: dict):
    user_json = json.dumps(payload, ensure_ascii=False, indent=2)
    if kind == "tarot":
        user_prompt = f"请做塔罗解读（娱乐用途）。输入信息如下（JSON）：\n{user_json}\n"
    elif kind == "zodiac":
        user_prompt = f"请做星座解读（娱乐用途）。输入信息如下（JSON）：\n{user_json}\n"
    else:
        user_prompt = f"请做八字/五行倾向解读（娱乐用途）。输入信息如下（JSON）：\n{user_json}\n"

    return [
        {"role": "system", "content": SYSTEM_STYLE},
        {"role": "user", "content": user_prompt},
    ]

def generate_report_with_credits(uid: str, kind: str, payload: dict) -> str:
    ok = consume_one_credit(uid)
    if not ok:
        return "⚠️ 你的剩余次数为 0。请先去【购买次数】页面付款并提交，或让管理员给你加次数。"

    msgs = build_messages(kind, payload)
    return call_openai_messages(msgs)

# =========================
# Zodiac / Bazi helpers
# =========================
ZODIAC = ["白羊","金牛","双子","巨蟹","狮子","处女","天秤","天蝎","射手","摩羯","水瓶","双鱼"]

def stable_wuxing_from_datetime(date_str: str, time_str: str):
    seed = f"{date_str}|{time_str}"
    h = hashlib.md5(seed.encode("utf-8")).hexdigest()
    nums = [int(h[i:i+2], 16) for i in range(0, 10, 2)]  # 5 numbers
    total = sum(nums) + 1e-9
    vals = [round(x / total, 3) for x in nums]
    keys = ["木", "火", "土", "金", "水"]
    return dict(zip(keys, vals))


def _dominant_two(scores: dict):
    items = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    return items[0], items[1]

def draw_wuxing_wheel_roulette(scores: dict, rotation_deg: float = 0.0):
    """
    五行转盘（轮盘风格）
    - rotation_deg: 旋转角度（度），用来做“转动动画”
    """
    labels = list(scores.keys())  # ["木","火","土","金","水"]
    values = np.array([scores[k] for k in labels], dtype=float)
    total = values.sum() + 1e-9
    values = values / total

    # 角度分配（扇区大小按比例）
    angles = values * 2 * np.pi
    # 起始角（加 rotation）
    start = np.deg2rad(rotation_deg)

    fig = plt.figure(figsize=(6, 6))
    ax = fig.add_subplot(111, polar=True)
    ax.set_theta_direction(-1)     # 顺时针
    ax.set_theta_offset(np.pi/2)   # 0 度在正上方
    ax.set_yticklabels([])
    ax.set_xticklabels([])
    ax.grid(False)

    # 画扇区（bar）
    theta = start
    for lab, ang, val in zip(labels, angles, values):
        ax.bar(
            x=theta + ang/2,
            height=1.0,
            width=ang,
            bottom=0.0,
            alpha=0.35,
            align="center",
            linewidth=1
        )
        # 扇区文字放在外圈
        mid = theta + ang/2
        ax.text(mid, 1.08, f"{lab}\n{val:.2f}", ha="center", va="center", fontsize=12)
        theta += ang

    # 指针（固定在正上方）
    ax.annotate(
        "", xy=(0, 1.15), xytext=(0, 0.2),
        arrowprops=dict(arrowstyle="->", linewidth=3)
    )
    ax.set_title("五行轮盘（娱乐版）", pad=20, fontsize=16)

    return fig

# =========================
# Tarot (Interactive Draw)
# =========================
def _list_tarot_cards():
    """读取 tarot_major 下所有牌图，排除 back.png"""
    if not TAROT_DIR.exists():
        return []
    imgs = []
    for ext in ("*.jpg", "*.jpeg", "*.png", "*.webp"):
        imgs += list(TAROT_DIR.glob(ext))
    imgs = [p for p in imgs if p.name.lower() != "back.png"]
    imgs.sort()  # 依赖你文件名 00_.. 01_..排序
    return imgs

def _ensure_tarot_assets():
    if not TAROT_DIR.exists():
        st.error(f"没找到牌库文件夹：{TAROT_DIR}（请把 tarot_major/ 放到 app.py 同级并 push）")
        st.stop()
    if not TAROT_BACK.exists():
        st.error(f"没找到背面图：{TAROT_BACK}（需要 back.png）")
        st.stop()

    cards = _list_tarot_cards()
    if len(cards) < 22:
        st.warning(f"牌库图片数量不足：当前 {len(cards)} 张（建议 22 张 00~21）")
    return cards

def _card_name_from_filename(p: Path) -> str:
    base = p.stem  # 00_the_fool
    parts = base.split("_", 1)
    if len(parts) == 2:
        return parts[1].replace("_", " ").strip().title()
    return base.replace("_", " ").strip().title()

def _tarot_state_init():
    if "tarot_deck" not in st.session_state:
        st.session_state.tarot_deck = []
    if "tarot_drawn" not in st.session_state:
        st.session_state.tarot_drawn = [None, None, None]
    if "tarot_question" not in st.session_state:
        st.session_state.tarot_question = ""
    if "tarot_generated" not in st.session_state:
        st.session_state.tarot_generated = False

def tarot_reset():
    cards = _ensure_tarot_assets()
    st.session_state.tarot_deck = cards[:]
    random.shuffle(st.session_state.tarot_deck)
    st.session_state.tarot_drawn = [None, None, None]
    st.session_state.tarot_generated = False

def _draw_one(pos_idx: int):
    if st.session_state.tarot_drawn[pos_idx] is not None:
        return
    if not st.session_state.tarot_deck:
        tarot_reset()
    card = st.session_state.tarot_deck.pop()
    st.session_state.tarot_drawn[pos_idx] = card
    st.session_state.tarot_generated = False

def _all_drawn():
    return all(x is not None for x in st.session_state.tarot_drawn)

def tarot_page_interactive(uid: str):
    _tarot_state_init()
    _ensure_tarot_assets()

    if not st.session_state.tarot_deck:
        tarot_reset()

    st.subheader("🔮 塔罗抽卡（互动版）")
    st.session_state.tarot_question = st.text_input(
        "你想问什么？（可选）",
        value=st.session_state.tarot_question,
        placeholder="例如：我和他还有可能吗？"
    )

    colA, colB = st.columns([1, 1])
    with colA:
        if st.button("🔄 重新洗牌/重抽", use_container_width=True):
            tarot_reset()
            st.rerun()
    with colB:
        st.caption("提示：请凭直觉依次点击三张背面牌来抽卡。")

    st.markdown("### 点击背面牌抽卡（过去 / 现在 / 未来）")
    c1, c2, c3 = st.columns(3)
    cols = [c1, c2, c3]

    for i, col in enumerate(cols):
        with col:
            st.caption(TAROT_POS_LABELS[i])
            drawn = st.session_state.tarot_drawn[i]
            if drawn is None:
                st.image(str(TAROT_BACK), use_container_width=True)
                if st.button(f"抽这张（{TAROT_POS_LABELS[i]}）", key=f"draw_{i}", use_container_width=True):
                    _draw_one(i)
                    st.rerun()
            else:
                st.image(str(drawn), use_container_width=True)
                st.write(f"**{_card_name_from_filename(drawn)}**")

    st.divider()
    if not _all_drawn():
        st.info("还没抽完三张牌：请把【过去 / 现在 / 未来】都抽出来。")
        return

    # 抽完后显示 payload
    payload = {
        "type": "tarot_reading",
        "spread": "past_present_future",
        "question": st.session_state.tarot_question.strip(),
        "cards": [
            {"position": TAROT_POS_LABELS[i], "card": _card_name_from_filename(st.session_state.tarot_drawn[i])}
            for i in range(3)
        ],
        "style": "温柔安慰，不制造焦虑；语气像真人占卜师；给出可执行的小建议；避免绝对化断言。"
    }

    st.markdown("#### 你抽到的牌（摘要）")
    st.write(" / ".join([f"{x['position']}：{x['card']}" for x in payload["cards"]]))

    if st.button("✨ 生成解读（消耗 1 次）", use_container_width=True):
        # 只在这里扣次数
        if get_credits(uid) <= 0:
            st.warning("你当前剩余次数为 0。请先去【购买次数】页面扫码付款，然后让管理员给你加次数。")
            return

        txt = generate_report_with_credits(uid, kind="tarot", payload=payload)
        st.session_state.tarot_generated = True
        st.markdown("## 🧾 解读结果")
        st.write(txt)

# =========================
# Pages: Zodiac / Bazi / Buy / Admin
# =========================
def page_zodiac(uid: str):
    st.subheader("♈ 星座解读（互动版）")
    sun = st.selectbox("太阳星座", ZODIAC)
    col1, col2 = st.columns(2)
    with col1:
        moon = st.selectbox("月亮星座（可选）", ["不填"] + ZODIAC)
    with col2:
        rising = st.selectbox("上升星座（可选）", ["不填"] + ZODIAC)

    tags = st.multiselect("你想看哪些方向？", ["感情", "事业/学业", "财运", "人际", "情绪/压力", "自我成长"])
    detail = st.text_area("补充信息（可选）", placeholder="比如：最近在纠结是否要分手/换工作…")

    if st.button("✨ 生成星座解读（消耗 1 次）", use_container_width=True):
        if get_credits(uid) <= 0:
            st.warning("你当前剩余次数为 0。请先去【购买次数】页面扫码付款，然后让管理员给你加次数。")
            return
        payload = {"kind": "zodiac", "sun": sun, "moon": moon, "rising": rising, "tags": tags, "detail": detail}
        txt = generate_report_with_credits(uid, kind="zodiac", payload=payload)
        st.markdown("## 🧾 解读结果")
        st.write(txt)

def page_bazi(uid: str):
    st.subheader("🎴 八字 / 五行轮盘（娱乐版）")
    d = st.date_input("出生日期")
    t = st.time_input("出生时间（可大概）")
    gender = st.selectbox("性别（可选）", ["不填", "男", "女"])
    focus = st.selectbox("你想重点看什么？", ["综合", "感情", "事业/学业", "财运", "情绪/状态", "人际关系"])
    detail = st.text_area("补充信息（可选）", placeholder="比如：最近的困扰/目标是什么？")

    scores = stable_wuxing_from_datetime(str(d), str(t))

# 初始化轮盘状态
    if "bazi_rotation" not in st.session_state:
        st.session_state.bazi_rotation = 0.0
    if "bazi_spun" not in st.session_state:
        st.session_state.bazi_spun = False

    wheel_box = st.empty()
    wheel_box.pyplot(draw_wuxing_wheel_roulette(scores, rotation_deg=st.session_state.bazi_rotation),
                    use_container_width=True)

    colA, colB = st.columns([1, 1])
    with colA:
        if st.button("🎡 开始轮盘推演（更有仪式感）", use_container_width=True):
            # 做一个“伪随机但稳定”的停点：跟生日时间绑定，这样每次打开结果一致（更像“命盘固定”）
            seed = f"{d}|{t}|{gender}"
            h = int(hashlib.md5(seed.encode("utf-8")).hexdigest()[:8], 16)
            target = (h % 360)  # 0~359 度

            # 动画：从当前角度开始，快速转几圈再慢慢停
            cur = float(st.session_state.bazi_rotation)
            total_steps = 36

            for i in range(total_steps):
                # 前快后慢
                speed = 40 - int(30 * (i / (total_steps - 1)))  # 40 -> 10
                cur = (cur + speed) % 360
                wheel_box.pyplot(draw_wuxing_wheel_roulette(scores, rotation_deg=cur),
                                use_container_width=True)
                time.sleep(0.05)

            # 最后落到 target（再“对齐”一次，仪式感强）
            cur = (target) % 360
            st.session_state.bazi_rotation = cur
            st.session_state.bazi_spun = True
            wheel_box.pyplot(draw_wuxing_wheel_roulette(scores, rotation_deg=cur),
                            use_container_width=True)

    with colB:
        st.caption("提示：这是“娱乐版轮盘仪式感”，不是真实排盘。结果会跟生日时间绑定，体验更像固定命盘。")

    # 转完后展示结果摘要
    main1, main2 = _dominant_two(scores)
    if st.session_state.bazi_spun:
        st.success(f"轮盘已定格：主五行偏向 **{main1[0]}**，其次 **{main2[0]}**（仅娱乐）")
    else:
        st.info("你可以先点一次【开始轮盘推演】再生成解读。")


    if st.button("✨ 生成八字/五行解读（消耗 1 次）", use_container_width=True):
      if not st.session_state.bazi_spun:
          st.warning("建议先点【开始轮盘推演】让轮盘定格，再生成解读（更有仪式感）。")
          st.stop()

      if get_credits(uid) <= 0:
          st.warning("你当前剩余次数为 0。请先去【购买次数】页面扫码付款，然后让管理员给你加次数。")
          return

      payload = {
          "kind": "bazi",
          "birth_date": str(d),
          "birth_time": str(t),
          "gender": gender,
          "focus": focus,
          "detail": detail,
          "wuxing_scores": scores,
          "roulette_rotation_deg": st.session_state.bazi_rotation,
          "dominant": {"top1": main1, "top2": main2},
      }
      txt = generate_report_with_credits(uid, kind="bazi", payload=payload)
      st.markdown("## 🧾 解读结果")
      st.write(txt)


def page_buy(uid: str):
    st.subheader("💳 购买次数（手动确认版）")
    st.write(f"单次价格：**¥{PRICE_YUAN}**，每次购买增加 **{CREDITS_PER_PAY} 次**")
    st.write("付款后在下方提交备注（可选），然后让管理员在【管理员】页给你加次数。")

    qr = Path(WECHAT_QR_PATH)
    if qr.exists():
        st.image(str(qr), caption="微信收款码（付款后请填写交易单号/备注）", use_container_width=True)
    else:
        st.warning(f"未找到收款码图片：{WECHAT_QR_PATH}（请放到仓库根目录）")

    note = st.text_input("交易单号/备注（可选）", placeholder="比如：12/26 19:30 微信订单xxxx 或 留空")
    if st.button("✅ 我已付款，提交记录", use_container_width=True):
        log_pay_intent(uid, amount=PRICE_YUAN, note=note)
        st.success("已提交！请把你的 user_id 发给管理员（或截图给你自己），管理员会给你加次数。")

    st.info("提示：你也可以把页面 URL 复制给朋友（里面包含 uid），这样他下次打开还是同一个 ID。")

def page_admin(uid: str):
    st.subheader("🛠 管理员面板：加次数 / 查看记录")

    if not ADMIN_PASSWORD:
        st.error("未设置 ADMIN_PASSWORD。请在 secrets 里配置 ADMIN_PASSWORD。")
        return

    pwd = st.text_input("管理员密码", type="password")
    if pwd != ADMIN_PASSWORD:
        st.info("输入管理员密码后才会显示操作。")
        return

    st.success("管理员已验证 ✅")

    st.markdown("### 给某个 user_id 加次数")
    target = st.text_input("user_id（用户会在左侧栏看到）", placeholder="例如：43B2DA34")
    n = st.number_input("增加次数", min_value=1, max_value=100, value=1, step=1)
    if st.button("✅ 确认加次数", use_container_width=True):
        if not target.strip():
            st.warning("请先输入 user_id")
        else:
            newv = add_credits(target.strip().upper(), int(n))
            st.success(f"已给 {target.strip().upper()} 加 {int(n)} 次，当前次数：{newv}")

    st.markdown("---")
    st.markdown("### credits.json（快速排查）")
    st.code(json.dumps(load_json(CREDITS_FILE, {}), ensure_ascii=False, indent=2)[:4000])

    st.markdown("---")
    st.markdown("### 最近付款提交记录（pay_reports.json）")
    rows = read_pay_reports(limit=50)
    if not rows:
        st.info("暂无提交记录。")
    else:
        for r in reversed(rows[-50:]):
            st.write(f"- [{r.get('submitted_at')}] uid={r.get('user_id')} amount={r.get('amount')} status={r.get('status')} note={r.get('note')}")

# =========================
# Sidebar + Router
# =========================
st.title(APP_TITLE)

uid = get_or_create_user_id()
credits = get_credits(uid)

with st.sidebar:
    st.header("菜单")
    st.write(f"你的用户ID：`{uid}`")
    st.write(f"剩余次数：**{credits}**")

    st.caption("⚠️ 提示：换浏览器/清缓存可能会生成新 ID。")
    st.caption("建议：把 URL 复制收藏（含 uid），或在下方手动输入固定 ID。")

    fixed = st.text_input("手动输入你的 user_id（固定登录）", value=uid)
    if st.button("🔒 使用这个 user_id"):
        set_user_id(fixed)
        st.rerun()

    st.markdown("---")
    page = st.radio("选择页面", ["生成报告", "购买次数", "管理员"])

    st.markdown("---")
    st.caption("免责声明：本应用内容仅供娱乐与自我反思，不替代医疗/法律/投资建议。")

if not OPENAI_API_KEY:
    st.error("缺少 OPENAI_API_KEY。请在 Streamlit Cloud Secrets 或本地 .streamlit/secrets.toml 设置。")
    st.stop()

if page == "购买次数":
    page_buy(uid)
elif page == "管理员":
    page_admin(uid)
else:
    tab1, tab2, tab3 = st.tabs(["🃏 塔罗", "♈ 星座", "🎴 八字/五行"])
    with tab1:
        tarot_page_interactive(uid)
    with tab2:
        page_zodiac(uid)
    with tab3:
        page_bazi(uid)