# -*- coding: utf-8 -*-
"""OpenAI_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTIyyJPTtoYy6_JNfBNbkYRKc6ntOAHI
"""

import os
import json
import time
import secrets
from datetime import datetime
import requests
import streamlit as st
from pathlib import Path


qr_path = Path("assets/wechat_qr.png")

if qr_path.exists():
    st.image(str(qr_path), caption="微信收款码（支付后请填写交易单号/备注）", use_container_width=True)
else:
    st.warning("未找到收款码图片：assets/wechat_qr.png")
# =========================
# App Config
# =========================
st.set_page_config(page_title="玄学小助手（单次付费）", page_icon="🔮", layout="wide")
APP_TITLE = "🔮 玄学小助手（八字 / 星座 / 塔罗）"

DEFAULT_MODEL = "gpt-4.1-mini"   # 你也可以改成别的
PRICE_YUAN = "4.99"             # 单次价格
CREDITS_PER_PAY = 1             # 每次付款增加的次数

CREDITS_FILE = "credits.json"
REPORTS_FILE = "pay_reports.jsonl"
WECHAT_QR_FILE = "wechat_qr.png"

# =========================
# Secrets / API key
# =========================
OPENAI_API_KEY = None
if "OPENAI_API_KEY" in st.secrets:
    OPENAI_API_KEY = st.secrets["OPENAI_API_KEY"]
else:
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

ADMIN_PASSWORD = st.secrets.get("ADMIN_PASSWORD", os.getenv("ADMIN_PASSWORD", ""))

if not OPENAI_API_KEY:
    st.error("缺少 OPENAI_API_KEY。请在本地 .streamlit/secrets.toml 或 Streamlit Cloud Secrets 中设置。")
    st.stop()

# =========================
# Helpers: user id (no login)
# =========================
def get_or_create_user_id() -> str:
    # 不用登录：用 session 自动分配一个短ID（用户刷新/换设备可能会变）
    if "user_id" not in st.session_state:
        st.session_state["user_id"] = secrets.token_hex(4).upper()  # 8 hex bytes -> 8 chars
    return st.session_state["user_id"]

def new_order_code() -> str:
    return secrets.token_hex(2).upper()

# =========================
# Helpers: JSON storage
# =========================
def load_json(path: str, default):
    try:
        if not os.path.exists(path):
            return default
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return default

def save_json(path: str, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

# =========================
# Credits (pay-per-use)
# =========================
def get_credits(user_id: str) -> int:
    d = load_json(CREDITS_FILE, {})
    return int(d.get(user_id, 0))

def add_credits(user_id: str, n: int) -> int:
    d = load_json(CREDITS_FILE, {})
    d[user_id] = int(d.get(user_id, 0)) + int(n)
    save_json(CREDITS_FILE, d)
    return int(d[user_id])

def consume_credits(user_id: str, n: int = 1):
    d = load_json(CREDITS_FILE, {})
    cur = int(d.get(user_id, 0))
    if cur < n:
        return False, cur
    d[user_id] = cur - n
    save_json(CREDITS_FILE, d)
    return True, int(d[user_id])

# =========================
# OpenAI Responses API (no openai pip needed)
# =========================
def extract_text(resp: dict) -> str:
    # Most common: output_text
    if resp.get("output_text"):
        return resp["output_text"]
    # Fallback parse output blocks
    out = []
    for item in resp.get("output", []):
        for c in item.get("content", []):
            if c.get("type") in ("output_text", "text") and "text" in c:
                out.append(c["text"])
    return "\n".join(out).strip()

def openai_responses(messages, model=DEFAULT_MODEL, timeout=60) -> str:
    r = requests.post(
        "https://api.openai.com/v1/responses",
        headers={
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": "application/json",
        },
        json={"model": model, "input": messages},
        timeout=timeout,
    )
    if r.status_code != 200:
        return f"HTTP {r.status_code}\n{r.text[:1500]}"
    return extract_text(r.json()) or "(empty)"

# =========================
# Prompt builders (gentle style)
# =========================
BASE_SYSTEM = """你是一位温柔、安慰型的解读助手，擅长用温和的方式给予情绪支持与建设性建议。
你可以提供八字/星座/塔罗的“娱乐与自我反思向”的解读：语气温柔、有同理心、避免吓人或绝对化判断。
不要把用户的未来说死；多用“可能”“倾向”“建议”。
输出结构清晰：先总体→再分点→最后给温柔的行动建议。
必须包含一句免责声明：内容仅供娱乐与自我反思，不替代医疗/法律/投资建议。
"""

def build_msgs_for_bazi(payload: dict):
    # payload: birth date/time, gender, focus, extra
    user_content = f"""
请你根据以下信息做一份温柔、安慰型八字解读（偏性格/事业/感情/情绪与建议）。
信息：
- 公历生日：{payload.get('date','')}
- 出生时间：{payload.get('time','')}（如果不确定也要说明）
- 出生地（可选）：{payload.get('place','')}
- 性别（可选）：{payload.get('gender','')}
- 关注点：{payload.get('focus','')}
- 用户补充：{payload.get('extra','')}

要求：
1) 不要装作你“确定算出精确八字排盘”如果信息不全；信息不足时用“趋势解读 + 建议”。
2) 给出 3-5 条温柔可执行建议（比如作息、人际、学习、情绪照顾）。
3) 风格温柔，不恐吓、不绝对化。
"""
    return [
        {"role": "system", "content": BASE_SYSTEM},
        {"role": "user", "content": user_content.strip()},
    ]

def build_msgs_for_zodiac(payload: dict):
    user_content = f"""
请你根据以下信息做一份温柔、安慰型星座解读（偏性格/关系/近期状态与建议）。
信息：
- 生日：{payload.get('birthday','')}（公历）
- 星座（如果用户写了）：{payload.get('sign','')}
- 上升（可选）：{payload.get('rising','')}
- 月亮（可选）：{payload.get('moon','')}
- 关注点：{payload.get('focus','')}
- 用户补充：{payload.get('extra','')}

要求：
1) 信息不全就用“通用但具体的建议”，不要强装精准。
2) 给出 3-5 条温柔可执行建议。
3) 风格温柔，不恐吓、不绝对化。
"""
    return [
        {"role": "system", "content": BASE_SYSTEM},
        {"role": "user", "content": user_content.strip()},
    ]

def build_msgs_for_tarot(payload: dict):
    user_content = f"""
你是一位温柔的塔罗解读者。请根据用户给出的“问题 + 抽到的牌”做解读。
信息：
- 用户问题：{payload.get('question','')}
- 牌阵：{payload.get('spread','')}（例如 三张：过去/现在/建议）
- 抽到的牌（用户输入，按顺序）：{payload.get('cards','')}
- 是否有逆位：{payload.get('reversed','')}（如果用户没写就当未知）
- 用户补充：{payload.get('extra','')}

输出结构：
1) 先用 2-3 句话温柔回应用户情绪与处境（不要评判）。
2) 分位置解释（按牌阵位置逐条讲），每条包含：象征→可能含义→温柔建议。
3) 最后给“今天/这周可以做的 3 条小行动”。
4) 加免责声明（娱乐与自我反思）。
"""
    return [
        {"role": "system", "content": BASE_SYSTEM},
        {"role": "user", "content": user_content.strip()},
    ]

# =========================
# Pages
# =========================
def buy_page(user_id: str):
    st.subheader(f"购买 1 次（¥{PRICE_YUAN}）")

    # 每次打开购买页生成一个新的 order_code（避免复用）
    if st.button("生成新的付款备注（推荐）"):
        st.session_state["order_code"] = new_order_code()

    order_code = st.session_state.get("order_code") or new_order_code()
    st.session_state["order_code"] = order_code

    note = f"ORDER|{user_id}|{CREDITS_PER_PAY}|{order_code}"
    st.write("请扫码付款，并在【付款备注】里写（复制这行）：")
    st.code(note)

    c1, c2 = st.columns([1, 1.3])
    with c1:
        if os.path.exists(WECHAT_QR_FILE):
            st.image(WECHAT_QR_FILE, width=280, caption="微信收款码")
        else:
            st.warning("未找到 wechat_qr.png：把你的微信收款码图片放到 app.py 同目录即可。")
    with c2:
        st.markdown(
            f"""
**说明：**
- 单次价格：**¥{PRICE_YUAN}**（= 1 次生成）
- 备注必须包含你的用户ID：`{user_id}`
- 提交后我确认到账，会给你加 1 次（可重复购买追加次数）
"""
        )

    st.divider()
    st.markdown("### 我已付款（提交信息）")
    with st.form("pay_report"):
        st.text_input("金额（参考）", value=PRICE_YUAN, disabled=True)
        pay_time = st.text_input("付款时间（例如 12/19 21:30）")
        note_input = st.text_input("你填写的备注（保持一致）", value=note)
        wechat_name = st.text_input("微信昵称（可选）")
        submit = st.form_submit_button("提交")
    if submit:
        rec = {
            "user_id": user_id,
            "credits": CREDITS_PER_PAY,
            "amount": PRICE_YUAN,
            "pay_time": pay_time,
            "note": note_input,
            "wechat_name": wechat_name,
            "status": "pending",
            "submitted_at": datetime.now().isoformat(timespec="seconds"),
        }
        with open(REPORTS_FILE, "a", encoding="utf-8") as f:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
        st.success("已提交！我确认到账后会给你加 1 次。你可以稍后刷新查看剩余次数。")

def admin_panel():
    st.subheader("管理员面板：加次数")
    if not ADMIN_PASSWORD:
        st.warning("未设置 ADMIN_PASSWORD。请在 secrets.toml 或 Cloud Secrets 里设置。")
        return

    pwd = st.text_input("管理员密码", type="password")
    if pwd != ADMIN_PASSWORD:
        st.info("输入管理员密码后可操作。")
        return

    st.markdown("### 给某个 user_id 加次数")
    uid = st.text_input("user_id（用户侧会显示）")
    n = st.number_input("增加次数", min_value=1, max_value=100, value=1)
    if st.button("✅ 确认加次数"):
        newv = add_credits(uid.strip(), int(n))
        st.success(f"已添加：{uid} 当前次数 = {newv}")

    st.divider()
    st.markdown("### 查看 credits.json（快速排查）")
    if st.button("刷新查看"):
        pass
    st.code(json.dumps(load_json(CREDITS_FILE, {}), ensure_ascii=False, indent=2)[:3000])

def generator_page(user_id: str):
    st.subheader("生成解读")
    st.caption("温柔安慰风格｜内容仅供娱乐与自我反思，不替代医疗/法律/投资建议。")

    credits = get_credits(user_id)
    st.info(f"你的用户ID：{user_id} ｜ 剩余次数：{credits}")

    if credits <= 0:
        st.warning("你当前剩余次数为 0。请先去【购买次数】扫码付款。")
        st.stop()

    kind = st.selectbox("选择类型", ["八字", "星座", "塔罗"])
    focus = st.selectbox("关注点（可选）", ["综合", "感情", "事业/学业", "财运", "情绪/状态", "人际关系"])

    payload = {"focus": focus}
    if kind == "八字":
        c1, c2, c3 = st.columns(3)
        with c1:
            payload["date"] = st.text_input("公历生日（YYYY-MM-DD）", placeholder="例如 1998-12-08")
        with c2:
            payload["time"] = st.text_input("出生时间（HH:MM，可不确定）", placeholder="例如 09:30 或 不确定")
        with c3:
            payload["gender"] = st.selectbox("性别（可选）", ["", "男", "女", "其他/不方便说"])
        payload["place"] = st.text_input("出生地（可选）", placeholder="例如 西安 / Chicago")
        payload["extra"] = st.text_area("补充信息（可选）", placeholder="例如：最近焦虑、感情进展、想问工作方向等")
        build = build_msgs_for_bazi

    elif kind == "星座":
        c1, c2 = st.columns(2)
        with c1:
            payload["birthday"] = st.text_input("生日（公历 YYYY-MM-DD）", placeholder="例如 1999-11-08")
            payload["sign"] = st.text_input("星座（可选）", placeholder="例如 天蝎座 / Scorpio（不确定可留空）")
        with c2:
            payload["rising"] = st.text_input("上升（可选）", placeholder="例如 上升狮子（不确定可留空）")
            payload["moon"] = st.text_input("月亮（可选）", placeholder="例如 月亮金牛（不确定可留空）")
        payload["extra"] = st.text_area("补充信息（可选）", placeholder="例如：最近的情感困扰、工作压力、想要的改变等")
        build = build_msgs_for_zodiac

    else:  # Tarot
        payload["question"] = st.text_input("你的问题（越具体越好）", placeholder="例如：我该不该接受这份工作？")
        payload["spread"] = st.selectbox("牌阵", ["三张：过去/现在/建议", "三张：我/对方/关系走向", "单张：今日指引", "自定义"])
        if payload["spread"] == "自定义":
            payload["spread"] = st.text_input("自定义牌阵描述", placeholder="例如：1现在 2障碍 3建议")
        payload["cards"] = st.text_area("抽到的牌（按顺序输入）", placeholder="例如：圣杯二 正位；宝剑十 逆位；权杖一 正位")
        payload["reversed"] = st.selectbox("是否包含逆位？", ["不确定/混合", "全正位", "有逆位"])
        payload["extra"] = st.text_area("补充信息（可选）", placeholder="例如：我现在的处境、担心点、希望得到的安慰/建议")
        build = build_msgs_for_tarot

    st.divider()

    if st.button("✨ 生成解读（扣 1 次）", type="primary"):
        # 先扣次数，避免刷接口；若失败则回滚
        ok, left = consume_credits(user_id, 1)
        if not ok:
            st.warning("次数不足，请先购买。")
            st.stop()

        msgs = build(payload)

        with st.spinner("正在生成…"):
            reply = openai_responses(msgs)

        # API 失败：回滚次数
        if reply.startswith("HTTP "):
            add_credits(user_id, 1)
            st.error("调用失败，已退回 1 次额度。错误信息：")
            st.code(reply)
            st.stop()

        st.success("生成完成 ✅")
        st.markdown(reply)

# =========================
# Main UI
# =========================
st.title(APP_TITLE)

user_id = get_or_create_user_id()
credits = get_credits(user_id)

with st.sidebar:
    st.header("菜单")
    st.write(f"你的用户ID：**{user_id}**")
    st.write(f"剩余次数：**{credits}**")
    st.caption("提示：换浏览器/清缓存可能会生成新ID，建议记下你的ID。")
    page = st.radio("选择页面", ["生成报告", "购买次数", "管理员"])

    st.divider()
    st.caption("免责声明：本应用内容仅供娱乐与自我反思，不替代医疗/法律/投资建议。")

if page == "购买次数":
    buy_page(user_id)
elif page == "管理员":
    admin_panel()
else:
    generator_page(user_id)