# -*- coding: utf-8 -*-
"""OpenAI_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTIyyJPTtoYy6_JNfBNbkYRKc6ntOAHI
"""

# app.py
import os, json, time, secrets, re
from datetime import datetime
from pathlib import Path

import requests
import streamlit as st

# =========================
# App Config
# =========================
st.set_page_config(page_title="玄学小助手（单次付费）", page_icon="🔮", layout="wide")

APP_TITLE = "🔮 玄学小助手（八字 / 星座 / 塔罗）"
DEFAULT_MODEL = "gpt-4.1-mini"
PRICE_YUAN = "4.99"
CREDITS_PER_PAY = 1

CREDITS_FILE = "credits.json"
REPORTS_FILE = "pay_reports.json"
WECHAT_QR_FILE = "wechat_qr.png"   # 放在 app.py 同级目录

UID_KEY = "uid"

# =========================
# Secrets / Keys
# =========================
def get_secret(name: str, default: str = "") -> str:
    # streamlit cloud: st.secrets
    # local: .streamlit/secrets.toml
    # fallback: env var
    if name in st.secrets:
        return str(st.secrets[name])
    return os.getenv(name, default)

OPENAI_API_KEY = get_secret("OPENAI_API_KEY", "")
ADMIN_PASSWORD = get_secret("ADMIN_PASSWORD", "")

if not OPENAI_API_KEY:
    st.error("缺少 OPENAI_API_KEY。请在 Streamlit Cloud 的 Secrets 或本地 .streamlit/secrets.toml 里配置。")
    st.stop()

# =========================
# Utility: JSON load/save
# =========================
def load_json(path: str, default):
    p = Path(path)
    if not p.exists():
        return default
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return default

def save_json(path: str, obj):
    Path(path).write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding="utf-8")

# =========================
# User ID: normalize / get / set
# =========================
def normalize_uid(s: str) -> str:
    s = (s or "").strip()
    # 允许：中文/英文/数字/下划线/短横线，长度 2~32
    s = re.sub(r"[^\w\u4e00-\u9fff\-]", "", s)
    return s[:32]

def get_user_id() -> str:
    # 1) URL 参数优先（分享链接带 ?uid=xxx）
    qp = st.query_params
    if UID_KEY in qp and qp[UID_KEY]:
        uid = normalize_uid(qp[UID_KEY])
        if uid:
            st.session_state[UID_KEY] = uid
            return uid

    # 2) session_state
    uid = normalize_uid(st.session_state.get(UID_KEY, ""))
    if uid:
        return uid

    # 3) 兜底：自动生成 8 位
    uid = secrets.token_hex(4).upper()
    st.session_state[UID_KEY] = uid
    st.query_params[UID_KEY] = uid
    return uid

def set_user_id(uid: str):
    uid = normalize_uid(uid)
    if len(uid) < 2:
        return False, "ID 太短了（至少 2 位）。建议：手机后4位+昵称，例如 1108_jiuming。"
    st.session_state[UID_KEY] = uid
    st.query_params[UID_KEY] = uid
    return True, f"✅ 已切换用户ID：{uid}"

# =========================
# Credits
# =========================
def get_credits(user_id: str) -> int:
    credits = load_json(CREDITS_FILE, {})
    return int(credits.get(user_id, 0))

def add_credits(user_id: str, n: int):
    credits = load_json(CREDITS_FILE, {})
    credits[user_id] = int(credits.get(user_id, 0)) + int(n)
    save_json(CREDITS_FILE, credits)
    return credits[user_id]

def spend_credits(user_id: str, n: int = 1):
    credits = load_json(CREDITS_FILE, {})
    cur = int(credits.get(user_id, 0))
    if cur < n:
        return False, cur
    credits[user_id] = cur - n
    save_json(CREDITS_FILE, credits)
    return True, credits[user_id]

# =========================
# OpenAI call (Responses API)
# =========================
def extract_output_text(resp_json: dict) -> str:
    # 兼容 output_text / output[].content[].text
    if isinstance(resp_json, dict) and resp_json.get("output_text"):
        return resp_json["output_text"]

    out = []
    for item in (resp_json.get("output") or []):
        for c in (item.get("content") or []):
            if c.get("type") in ("output_text", "text") and "text" in c:
                out.append(c["text"])
    return "\n".join(out).strip()

def call_openai(msgs, model=DEFAULT_MODEL, timeout=60):
    url = "https://api.openai.com/v1/responses"
    headers = {
        "Authorization": f"Bearer {OPENAI_API_KEY}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "input": msgs,
    }
    r = requests.post(url, headers=headers, json=payload, timeout=timeout)
    if r.status_code != 200:
        return f"❌ OpenAI API 错误：HTTP {r.status_code}\n\n{r.text[:1200]}"
    return extract_output_text(r.json()) or "（空回复）"

# =========================
# Prompt builder
# =========================
MODES = {
    "温柔安慰": "你是一位温柔、共情、善于安慰的人。你会先理解用户情绪，再给出温柔而具体的建议。避免说教，语气柔和。",
    "八字": "你是一位风格温和、措辞谨慎的八字解读师。你会以娱乐与自我反思角度进行解读，不要绝对化断言，不涉及医疗/法律/投资建议。",
    "星座": "你是一位温柔、有趣但不夸张的星座解读师。以娱乐为主，给出可执行的小建议，避免绝对断言。",
    "塔罗": "你是一位温柔、尊重用户的塔罗解读师。强调这是自我探索，不做绝对预言。结构清晰：现状-阻碍-建议-提醒。",
}

DISCLAIMER = "免责声明：本应用内容仅供娱乐与自我反思，不构成医疗/法律/投资建议。"

def build_msgs(kind: str, user_text: str):
    system = MODES.get(kind, MODES["温柔安慰"])
    msgs = [
        {"role": "system", "content": system},
        {"role": "system", "content": DISCLAIMER},
        {"role": "user", "content": user_text},
    ]
    return msgs

# =========================
# UI: Sidebar (ID + menu)
# =========================
st.title(APP_TITLE)

user_id = get_user_id()
credits_left = get_credits(user_id)

st.sidebar.markdown("## 菜单")
st.sidebar.write(f"你的用户ID：`{user_id}`")
st.sidebar.write(f"剩余次数：**{credits_left}**")
st.sidebar.caption("提示：换浏览器/清缓存会导致ID变化；建议你手动设置固定ID。")

with st.sidebar.expander("切换/设置用户ID（推荐）", expanded=False):
    new_uid = st.text_input("输入你的固定ID", value=user_id, placeholder="例如：1108_jiuming / 手机后4位+昵称")
    if st.button("保存并切换"):
        ok, msg = set_user_id(new_uid)
        if ok:
            st.success(msg)
            st.rerun()
        else:
            st.error(msg)

page = st.sidebar.radio("选择页面", ["生成报告", "购买次数", "管理员"], index=0)

st.sidebar.divider()
st.sidebar.caption("部署给同学：把代码放 GitHub，再用 Streamlit Cloud 部署；Key 放 Cloud Secrets。")

# =========================
# Page: Buy
# =========================
def buy_page():
    st.header("购买次数")
    st.write(f"单次价格：**¥{PRICE_YUAN}**，每次购买增加 **{CREDITS_PER_PAY}** 次。")
    st.info(f"请把你的用户ID发给管理员加次数：`{user_id}`（建议截图）")

    qr_path = Path(WECHAT_QR_FILE)
    if qr_path.exists():
        st.image(str(qr_path), caption="微信收款码（付款后请把交易号/备注 + 用户ID 发给管理员）", use_container_width=True)
    else:
        st.warning(f"未找到收款码图片：{WECHAT_QR_FILE}（请放在 app.py 同级目录）")

    st.subheader("付款后我需要给管理员什么信息？")
    st.markdown(
        "- 你的 **用户ID**\n"
        "- 付款截图 或 交易号/备注（你可以让对方备注你的用户ID）\n"
        "- 付款次数（比如买 1 次 / 买 5 次）"
    )

# =========================
# Page: Admin
# =========================
def admin_page():
    st.header("管理员面板：加次数")

    if not ADMIN_PASSWORD:
        st.warning("未配置 ADMIN_PASSWORD。请在 Secrets 里设置 ADMIN_PASSWORD。")
        st.stop()

    pwd = st.text_input("管理员密码", type="password")
    if pwd != ADMIN_PASSWORD:
        st.info("输入管理员密码后才可操作。")
        st.stop()

    st.success("✅ 管理员已验证")

    st.subheader("给某个 user_id 加次数")
    uid = st.text_input("user_id（用户侧边栏会显示）", placeholder="例如：1108_jiuming")
    n = st.number_input("增加次数", min_value=1, max_value=100, value=1, step=1)

    # 关键：Streamlit 输入框不需要“回车”，要点按钮触发
    if st.button("✅ 确认加次数"):
        uid2 = normalize_uid(uid)
        if len(uid2) < 2:
            st.error("user_id 不合法（至少 2 位，只能中文/英文/数字/_/-）。")
        else:
            new_total = add_credits(uid2, int(n))
            st.success(f"已给 `{uid2}` 增加 {int(n)} 次。当前余额：{new_total}")

    st.divider()
    st.subheader("快速查看 credits.json（排查用）")
    if st.button("刷新查看"):
        pass
    st.code(json.dumps(load_json(CREDITS_FILE, {}), ensure_ascii=False, indent=2)[:6000])

    st.divider()
    st.subheader("付款记录 pay_reports.json（可选）")
    st.code(json.dumps(load_json(REPORTS_FILE, []), ensure_ascii=False, indent=2)[:6000])

# =========================
# Page: Generator
# =========================
def generator_page():
    st.header("生成报告")
    st.caption(DISCLAIMER)
    st.info(f"当前用户ID：`{user_id}`（建议你设置固定ID，避免换设备后次数丢失）")

    if credits_left <= 0:
        st.warning("你当前剩余次数为 0，请先去【购买次数】页面付款，然后联系管理员加次数。")
        st.stop()

    kind = st.selectbox("选择类型", ["温柔安慰", "八字", "星座", "塔罗"], index=0)
    topic = st.selectbox("关注点（可选）", ["综合", "感情", "学业/事业", "财运", "情绪/状态", "人际关系"], index=0)

    st.write("请尽量提供清晰信息（越具体越好）：")
    user_text = st.text_area(
        "输入信息",
        height=180,
        placeholder="例如：\n- 星座：天蝎座，最近情绪很低，想知道感情怎么走\n- 八字：xxxx-xx-xx xx:xx 出生，地点xx，关注事业\n- 塔罗：我抽到 XX、XX、XX，问xxx"
    )

    col1, col2 = st.columns([1, 1])
    with col1:
        go = st.button("🔮 生成（消耗 1 次）", use_container_width=True)
    with col2:
        st.write("")

    if go:
        text = user_text.strip()
        if not text:
            st.error("请先输入信息。")
            st.stop()

        ok, remain = spend_credits(user_id, 1)
        if not ok:
            st.error("次数不足，请先购买。")
            st.stop()

        prompt = f"[类型]{kind}\n[关注点]{topic}\n[用户输入]\n{text}"
        msgs = build_msgs(kind, prompt)

        with st.spinner("正在生成..."):
            ans = call_openai(msgs)

        st.success(f"✅ 已生成。剩余次数：{remain}")
        st.markdown("### 结果")
        st.write(ans)

# =========================
# Router
# =========================
if page == "生成报告":
    generator_page()
elif page == "购买次数":
    buy_page()
else:
    admin_page()